displayName=Loot Bank Filter
author=Lathenso
description=Tracks session loot per source and filters the bank to show only looted items
tags=loot,tracker,bank,filter,search
plugins=com.lootbankfilter.LootBankFilterPlugin
version=
build=standard
